// Generated by scripts/ci/generate-openapi-client.mjs; DO NOT EDIT.
export type Problem = { type: string; title: string; status: number; detail?: string; instance?: string };
export type RequestOptions = { headers?: Record<string, string>; body?: unknown };
export class OpenRevenueClient {
  constructor(private readonly baseUrl: string, private readonly request: typeof fetch = fetch) {}
  async createTaxpayer(options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/taxpayers`, { method: "POST", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async getTaxpayer(taxpayerId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/taxpayers/${encodeURIComponent(taxpayerId)}`, { method: "GET", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async registerTaxpayer(taxpayerId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/taxpayers/${encodeURIComponent(taxpayerId)}/tax-registrations`, { method: "POST", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async getTaxRegistration(registrationId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/tax-registrations/${encodeURIComponent(registrationId)}`, { method: "GET", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async approveTaxRegistration(registrationId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/tax-registrations/${encodeURIComponent(registrationId)}/approve`, { method: "POST", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async createReturnDraft(options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/returns`, { method: "POST", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async getReturn(returnId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/returns/${encodeURIComponent(returnId)}`, { method: "GET", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async validateReturn(returnId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/returns/${encodeURIComponent(returnId)}/validate`, { method: "POST", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async calculateReturn(returnId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/returns/${encodeURIComponent(returnId)}/calculate`, { method: "POST", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async submitReturn(returnId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/returns/${encodeURIComponent(returnId)}/submit`, { method: "POST", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async amendReturn(returnId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/returns/${encodeURIComponent(returnId)}/amend`, { method: "POST", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async getReturnHistory(returnId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/returns/${encodeURIComponent(returnId)}/history`, { method: "GET", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async recordPayment(options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/payments`, { method: "POST", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async getPayment(paymentId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/payments/${encodeURIComponent(paymentId)}`, { method: "GET", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async allocatePayment(paymentId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/payments/${encodeURIComponent(paymentId)}/allocations`, { method: "POST", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async getAssessment(assessmentId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/assessments/${encodeURIComponent(assessmentId)}`, { method: "GET", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async getLedger(taxpayerId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/taxpayers/${encodeURIComponent(taxpayerId)}/ledger`, { method: "GET", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async reverseLedgerPosting(postingId: string, options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/ledger/postings/${encodeURIComponent(postingId)}/reverse`, { method: "POST", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
  async listAuditEvents(options: RequestOptions = {}): Promise<unknown> {
    const response = await this.request(`${this.baseUrl}/admin/audit-events`, { method: "GET", headers: options.headers, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
    if (!response.ok) throw await response.json() as Problem;
    return response.status === 204 ? undefined : response.json();
  }
}
